plugins {
  id("java")
  id("org.springframework.boot") version "3.1.0" apply false
  id("io.spring.dependency-management") version "1.1.4" apply false
}

allprojects {
  apply plugin: "java"

  group = "uk.co.fivium"
  version = "0.0.1-SNAPSHOT"

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }
}

subprojects {
  apply plugin: "checkstyle"
  apply plugin: "io.spring.dependency-management"

  repositories {
    mavenCentral()
  }

  java {
    withSourcesJar()
    withJavadocJar()
  }

  checkstyle {
    config = rootProject.resources.text.fromFile('devtools/checkstyle.xml')
    toolVersion '9.3'
    ignoreFailures = false
    maxWarnings = 0
  }
}
