spring:
  datasource:
    url: jdbc:tc:postgresql:14.3:///test_database
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  flyway:
    schemas: public

file-upload:
  s3:
    access-key:
    secret-token:
    signing-region:
    disable-ssl: true
    proxy:
      host:
      port:
  clamav:
    timeout: PT1M
  default-maximum-file-size: 50MB
  default-permitted-file-extensions:
    - pdf
    - htm
